# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-04 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
