# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-04 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180504_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='password',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
